In [1]:
# !pip3 install -U pip > /dev/null
# !pip3 install -U "bio-embeddings[all] @ git+https://github.com/sacdallago/bio_embeddings.git" > /dev/null

In [1]:
import numpy as np
from bio_embeddings.embed import SeqVecEmbedder, ProtTransBertBFDEmbedder


Bad key savefig.frameon in file /home/murphy/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 421 ('savefig.frameon : True')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.level in file /home/murphy/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 472 ('verbose.level  : silent      # one of silent, helpful, debug, debug-annoying')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.fileo in file /home/murphy/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 473 ('verbose.fileo  : sys.stdout  # a log filename, sys.stdout or sys.stderr')
You probably need to get an 

In [2]:
embedders = []
sequence = "MALLHSARVLSGVASAFHPGLAAAASARASSWWAHVEMGPPDPILGVTEAYKRDTNSKKMNLGVGAYRDDNGKPYVLPSVRKAEAQIAAKGLDKEYLPIGGLAEFCRASAELALGENSEVVKSGRFVTVQTISGTGALRIGASFLQRFFKFSRDVFLPKPSWGNHTPIFRDAGMQLQSYRYYDPKTCGFDFTGALEDISKIPEQSVLLLHACAHNPTGVDPRPEQWKEIATVVKKRNLFAFFDMAYQGFASGDGDKDAWAVRHFIEQGINVCLCQSYAKNMGLYGERVGAFTVICKDADEAKRVESQLKILIRPMYSNPPIHGARIASTILTSPDLRKQWLQEVKGMADRIIGMRTQLVSNLKKEGSTHSWQHITDQIGMFCFTGLKPEQVERLTKEFSIYMTKDGRISVAGVTSGNVGYLAHAIHQVTK"

In [5]:
seqs = [sequence[:8] for i in range(512)]



In [6]:

embdder = ProtTransBertBFDEmbedder()



In [9]:
embdder.embed('M')

/home/murphy/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py:2022: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,


array([[ 0.03059292,  0.02430925,  0.13635753, ..., -0.08684584,
        -0.11445857, -0.01298136]], dtype=float32)

In [10]:
embdder.embed('A')

/home/murphy/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py:2022: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,


array([[ 0.03052338,  0.02443236,  0.13625264, ..., -0.0868152 ,
        -0.11452949, -0.01304919]], dtype=float32)

In [15]:
type(embdder.embed(sequence))

numpy.ndarray

In [7]:
%%time

np.array([embdder.embed(seq).shape for seq in seqs])

/home/murphy/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py:2022: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,


CPU times: user 11 s, sys: 9.84 ms, total: 11 s
Wall time: 11 s


array([[   8, 1024],
       [   8, 1024],
       [   8, 1024],
       ...,
       [   8, 1024],
       [   8, 1024],
       [   8, 1024]])

In [10]:
%%time
embdder = SeqVecEmbedder()

emb = embdder.embed(seqs)
emb.shape

CPU times: user 46.5 s, sys: 2.13 s, total: 48.6 s
Wall time: 20.7 s


(3, 128, 1024)

In [13]:
%%time

emb = embdder.embed(seqs)

CPU times: user 237 ms, sys: 0 ns, total: 237 ms
Wall time: 236 ms


In [6]:
%%time

emb = embdder.embed(seqs)

NameError: name 'embdder' is not defined

In [11]:
embdder = ProtTransBertBFDEmbedder()

embdder.embed(seqs)

TypeError: expected string or bytes-like object

In [8]:


embedders.append(ProtTransBertBFDEmbedder())
embedders.append(SeqVecEmbedder())
embeddings = []
for embedder in embedders:
    embedding = embedder.embed(sequence)
    embeddings.append(embedding)

for embedding in embeddings:
    print(np.array(embedding).shape)

prottrans_bert_bfd.zip: 1.56GB [01:06, 23.6MB/s]                               
weights.hdf5: 374MB [00:16, 23.1MB/s]                              
options.json: 8.19kB [00:00, 56.9kB/s]
/home/murphy/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py:2022: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,


(430, 1024)
(3, 430, 1024)


In [10]:
type(embeddings[0])

numpy.ndarray